apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-hello-world.fullname" . }}
  labels:
    {{- include "spring-boot-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      # nodePort: {{ .Values.service.nodePort }}
      # {{- end }}
      protocol: TCP
  selector:
    {{- include "spring-boot-hello-world.selectorLabels" . | nindent 4 }}
